keys:
  - &jacob_nixos age1ekm5suakvqtxapudwy0cwjgafvywvtepnmlqjykxd9q9cl5jpghqqg9y6c
  - &jacob_mini age1p3tsxcsa70q09fz3clrnvjwfyne8v9e6nzdx965m5qs3e8v8heyq0grz8f
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *jacob_nixos
          - *jacob_mini
